# This file was generated by GoReleaser. DO NOT EDIT.
cask "feed" do
  name "feed"
  desc "Local-first RSS CLI"
  homepage "https://github.com/odysseus0/feed"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "feed"

  on_macos do
    on_intel do
      url "https://github.com/odysseus0/feed/releases/download/v#{version}/feed_#{version}_darwin_amd64.tar.gz"
      sha256 "247513917d05ea7d87f4cf376b6b646f6f3504e801264848679595f7c404cf29"
    end
    on_arm do
      url "https://github.com/odysseus0/feed/releases/download/v#{version}/feed_#{version}_darwin_arm64.tar.gz"
      sha256 "ac1ea77c2e9261c780019dd574a437b30b6c7fe9c5e521706692cf87b2c2dc27"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/odysseus0/feed/releases/download/v#{version}/feed_#{version}_linux_amd64.tar.gz"
      sha256 "f4e3379e4009a9be09ef8c4af43172a933b5e5c32ab749b2b78133c678ea2d3b"
    end
    on_arm do
      url "https://github.com/odysseus0/feed/releases/download/v#{version}/feed_#{version}_linux_arm64.tar.gz"
      sha256 "4d1648407f5481aa43fd04e1f70ad100b504c9e0d41ef8b678843994f129dc3f"
    end
  end

  # No zap stanza required
end
