# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Feed < Formula
  desc "RSS CLI for AI agents. Bring your own algorithm."
  homepage "https://github.com/odysseus0/feed"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odysseus0/feed/releases/download/v0.2.0/feed_0.2.0_darwin_amd64.tar.gz"
      sha256 "c76c3da92ae06b4122fa1deb9885baa1c741a1cb038a4f1a159ad2d8f40d50d4"

      def install
        bin.install "feed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odysseus0/feed/releases/download/v0.2.0/feed_0.2.0_darwin_arm64.tar.gz"
      sha256 "e67aa2ecb20f30f36e68927db10200aeadf0b63f0d292a5025bfc7b0d7b99612"

      def install
        bin.install "feed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/odysseus0/feed/releases/download/v0.2.0/feed_0.2.0_linux_amd64.tar.gz"
      sha256 "446ae97028bde20796e21589fc99178b12d5371c56bdea3d10200ccf83a0d6be"
      def install
        bin.install "feed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odysseus0/feed/releases/download/v0.2.0/feed_0.2.0_linux_arm64.tar.gz"
      sha256 "658188955eccad894e3896eca91ac5c8b9d8480cf1ffa2ca1ec6dba1725b2c78"
      def install
        bin.install "feed"
      end
    end
  end
end
